title: Amanda Rigdon
logo: ![](./Images/amanda_icon.jpg)
description: Hi there! My name is Amanda! I'm a wine information analyst looking to branch out into the world of data analytics.
show_downloads: true
theme: jekyll-theme-minimal
